Models/Agince.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;

namespace RoleProject.Models
{
    public class Agince
    {
        [Key]
        public int ID { get; set; }
        [Required]

        public string name { get; set; }

        private string Password_Agence;
        [Required]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string password { get { return Password_Agence; } set { Password_Agence = value; } }

        [NotMapped]
        [Display(Name = "Confirm Password")]
        [Compare("password", ErrorMessage = "The password and confirmation password do not match.")]
        [DataType(DataType.Password)]

        public string confirm_Password { get; set; }

        // collection of phone for agence
        [Display(Name =  "Phone Number")]
        [Required]
        public string phone_number { get; set; }
        [Required]
        public string city { get; set; }
        [Required]
        public string street { get; set; }
        [Display(Name ="photo of Agince")]
        public string photo_Agince { get; set; }
        [NotMapped]
        public HttpPostedFileBase photo_path { get; set; }
        // Collection of cars in Agince 
        public Collection<Car> Collection_Of_Car { get; set; }
        public virtual ApplicationUser userAccount { get; set; }
    }
}

Controllers/AginceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RoleProject.Models;

namespace RoleProject.Controllers
{
    public class AginceController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Agince
        public ActionResult Index()
        {

          
                return View(context.Agince.ToList());
           
        }

        // GET: Agince/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                var Agince = context.Agince.FirstOrDefault(ag => ag.ID == id);
                return View(Agince);
            }
            catch {
                return View();
            }
        }

        // GET: Agince/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agince/Create
        [HttpPost]
        public ActionResult Create( string password,Agince agince)
        {
            #region Old_Creat
            //try
            //{
            //    agince.password = password;  
            //    /*Add photo to Data Base*/
            //    string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
            //    string Extintion = Path.GetExtension(agince.photo_path.FileName);
            //    filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
            //    agince.photo_Agince =filename;
            //    filename = Path.Combine(Server.MapPath("~/images/"), filename);
            //    agince.photo_path.SaveAs(filename);
            //    //----------------------------//
            //    context.Agince.Add(agince);
            //    context.SaveChanges();
            //    return RedirectToAction("Index","Home");
            //}
            //catch
            //{
            //    return View("Create");
            //} 
            #endregion
            if (ModelState.IsValid)
            {
                /*Add photo to Data Base*/
                string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
                string Extintion = Path.GetExtension(agince.photo_path.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
                agince.photo_Agince = filename;
                filename = Path.Combine(Server.MapPath("~/images/"), filename);
                agince.photo_path.SaveAs(filename);
                //----------------------------//
                context.Agince.Add(agince);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agince);
        }
    
        // GET: Agince/Edit/5
        public ActionResult Edit(int? id)
        {
          
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agince aganis_Car = context.Agince.Find(id);
            if (aganis_Car == null)
            {
                return HttpNotFound();
            }
            return View(aganis_Car);
            
        }
        // POST: Agince/Edit/5
        [HttpPost]
        public ActionResult Edit(int id,Agince agince , string password)
        {
           
            try
            {
                var newAgince = context.Agince.FirstOrDefault(agince_ => agince_.ID == id);
                
                if (newAgince.password == password)
                {
                    newAgince.password = password;
                    newAgince.confirm_Password = password;
                    newAgince.name = agince.name;
                    newAgince.phone_number = agince.phone_number;
                    /*Add photo to Data Base*/
                    string filename = Path.GetFileNameWithoutExtension(agince.photo_path.FileName);
                    string Extintion = Path.GetExtension(agince.photo_path.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + Extintion;
                    newAgince.photo_Agince = filename;
                    filename = Path.Combine(Server.MapPath("~/images/"), filename);
                    agince.photo_path.SaveAs(filename);
                    //----------------------------//
                }
                else
                {
                    return View("Edit");
                }
               
              
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit");
            }
        }

        // GET: Agince/Delete/5
        public ActionResult Delete(int id)
        {
            var Deleted_Agince = context.Agince.FirstOrDefault(agince_ => agince_.ID == id);
            return View(Deleted_Agince);
        }

        // POST: Agince/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            try
            {

                var Deleted_Agince = context.Agince.FirstOrDefault(agince_ => agince_.ID == id);
                context.Agince.Remove(Deleted_Agince);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Agince/Create.cshtml
@using System.Configuration
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Agince",FormMethod.Post ,new {  enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Agince</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.city, "city", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="city" id="city" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.street, "street", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="street" id="street" class="form-control" />
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="number" name="phone_Number" id="phone_Number" class="form-control" />

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.confirm_Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.confirm_Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.confirm_Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="photo_path" id="photo_path" />

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Agince/Delete.cshtml
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agince</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

     

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
          Street
        </dt>

        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>

        <dt>
           photo
        </dt>

        <dd>
            
                <img src="~/images/@Model.photo_Agince" width="150" height="150" style="border-radius:50%" />
            
        </dd>

    </dl>

    @using (Html.BeginForm("Delete","Agince",FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Agince/Details.cshtml
@using RoleProject.Models
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Details";
   
   
}

<h2>Details</h2>

<div>
    <h4>Agince</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_Agince)
        </dt>
        <dd>
            <img src="~/images/@Model.photo_Agince"  width = "150"  height = "150" style="border-radius:50%" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>
            <dd>
                @Model.phone_number
            </dd>
        <dd>
           @Model.city
        </dd>
        <dd>
            @Model.street
        </dd>
    </dl>
</div>

<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Views/Agince/Edit.cshtml
@using System.Configuration
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Agince", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, "city", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="city" id="city" value="@Model.city" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.street, "street", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="street" id="street" value="@Model.street" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="phone_Number" id="phone_Number" value="@Model.phone_number" class="form-control" />

            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.confirm_Password,"Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="password" name="password" id="password" class="form-control" />
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo_path" id="photo_path" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Agince/Edit1.cshtml
@using RoleProject.Models;
@model RoleProject.Models.Agince

@{
    ViewBag.Title = "Edit1";
    ApplicationDbContext context = new ApplicationDbContext();
    phone_Number_Agince  phone =  context.phone_Number_Agince.Where(phone_ => phone_.Agince_Id == Model.ID).FirstOrDefault();
    Address  address =  context.Adress.Where(address_ => address_.agince_id == Model.ID).FirstOrDefault();
}

<h2>Edit1</h2>


@using (Html.BeginForm("Edit", "Agince", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Agince</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="Country" id="Country" class="form-control" value="@address.country" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, "city", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="city" id="city" class="form-control" value="@address.city" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, "street", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" name="street" id="street" class="form-control" value="@address.street" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="number" name="phone_Number" id="phone_Number" value="@phone.phone_number" class="form-control" />

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.photo_path, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="photo_path" id="photo_path" />

        </div>
    </div>
    
    <div class="col-md-10">
        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    </div>
    }


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/Agince/Index.cshtml
@using  RoleProject.Models
@model List<Agince>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <h4>Agince</h4>
    <hr />
    <table class="table table-hover">

        <tr>
            <th>
               agince Name
            </th>

            <th>
               Photo 
            </th>
            <th>
                city
            </th>
            <th>
                street
            </th>
            <th>
                phone number
            </th>
            <th>
               Others
            </th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>

                <td>
                    @item.name
                </td>

                <td>
                    <img src="~/images/@item.photo_Agince" width="150" height="150" style="border-radius:50%" />
                </td>
                <td>
                    @item.city
                </td>
                <td>
                    @item.street
                </td>
                <td>
                    @item.phone_number
                </td>
                <td>
                    <a href="/Agince/Edit/@item.ID">Edit</a>
               
                    <a href="/Agince/delete/@item.ID">delete</a>
                </td>

            </tr>
        }







    </table>
</div>
<p>
  
    @Html.ActionLink("Back to List", "Index")
</p>